from PyQt5 import QtWidgets, QtCore


class Ui_NotificationWindow(object):
    def setupUi(self, NotificationWindow):
        NotificationWindow.setObjectName("NotificationWindow")
        NotificationWindow.resize(532, 434)
        self.verticalLayoutWidget = QtWidgets.QWidget(NotificationWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 541, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.main_label.setObjectName("main_label")
        self.verticalLayout.addWidget(self.main_label)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.new_user_fio_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.new_user_fio_label.setObjectName("new_user_fio_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.new_user_fio_label)
        self.new_user_fio_text_field = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.new_user_fio_text_field.setObjectName("new_user_fio_text_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.new_user_fio_text_field)
        self.new_user_sex_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.new_user_sex_label.setObjectName("new_user_sex_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.new_user_sex_label)
        self.new_user_sex_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.new_user_sex_combo_box.setObjectName("new_user_sex_combo_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.new_user_sex_combo_box)
        self.new_user_type_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.new_user_type_label.setObjectName("new_user_type_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.new_user_type_label)
        self.new_user_type_combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.new_user_type_combo_box.setObjectName("new_user_type_combo_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.new_user_type_combo_box)
        self.new_user_save_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.new_user_save_btn.setObjectName("new_user_save_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.new_user_save_btn)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 511, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.last_note_date_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.last_note_date_label.setObjectName("last_note_date_label")
        self.horizontalLayout_2.addWidget(self.last_note_date_label)
        self.last_date_textfield = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.last_date_textfield.setEnabled(True)
        self.last_date_textfield.setReadOnly(True)
        self.last_date_textfield.setObjectName("last_date_textfield")
        self.horizontalLayout_2.addWidget(self.last_date_textfield)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 511, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.parent_last_note_date_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.parent_last_note_date_label.setObjectName("parent_last_note_date_label")
        self.horizontalLayout_3.addWidget(self.parent_last_note_date_label)
        self.parent_last_note_date_textfield = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.parent_last_note_date_textfield.setReadOnly(True)
        self.parent_last_note_date_textfield.setObjectName("parent_last_note_date_textfield")
        self.horizontalLayout_3.addWidget(self.parent_last_note_date_textfield)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.run_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout.addWidget(self.run_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NotificationWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(NotificationWindow)

    def retranslateUi(self, NotificationWindow):
        _translate = QtCore.QCoreApplication.translate
        NotificationWindow.setWindowTitle(_translate("NotificationWindow", "NotificationWindow"))
        self.main_label.setText(_translate("NotificationWindow", "Настройки параметров оповещения"))
        self.label_2.setText(_translate("NotificationWindow", "Добавить получателя"))
        self.new_user_fio_label.setText(_translate("NotificationWindow", "ФИО (полностью)"))
        self.new_user_sex_label.setText(_translate("NotificationWindow", "Пол"))
        self.new_user_type_label.setText(_translate("NotificationWindow", "Тип пользователя"))
        self.new_user_save_btn.setText(_translate("NotificationWindow", "Сохранить пользователя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("NotificationWindow", "Общие"))
        self.last_note_date_label.setText(_translate("NotificationWindow", "Последняя расылка производилась"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("NotificationWindow", "Администрация"))
        self.parent_last_note_date_label.setText(_translate("NotificationWindow", "Последняя расылка производилась"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("NotificationWindow", "Родители"))
        self.save_btn.setText(_translate("NotificationWindow", "Сохранить"))
        self.run_btn.setText(_translate("NotificationWindow", "Запустить процедуру оповещения"))
